# hugo
baseURL: "https://note.sarisia.cc/"
languageCode: "en-us"
title: "NOTE.SARISIA.CC"
theme: zozo
hasCJKLanguage: true
googleAnalytics: "UA-99257943-2"
enableRobotsTXT: true
pygmentsUseClasses: true
pygmentsCodeFences: true

# routing
permalinks:
  entry: /entry/:slug/

# menu
menu:
  main:
    - name: POSTS
      weight: 10
      url: "/entry/"
    - name: TAGS
      weight: 20
      url: "/tags/"
    - name: SARISIA.CC
      weight: 30
      url: "https://sarisia.cc/"

# theme: zozo
params:
  enableSummary: true
social:
  github: "https://github.com/sarisia"
  twitter: "https://twitter.com/A1ces"
