name: deploy to github pages
on:
  workflow_dispatch:
    inputs:
      hugo-build-future:
        description: Build future (yes or no)
        required: false
        default: 'no'
  schedule:
    - cron: '0 15 * * *' # JST (UTC+9)
  push:
    branches:
      - master
    tags-ignore:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.0'
      - name: determine build mode
        id: hugo-build-mode
        if: github.event.inputs.hugo-build-future == 'yes'
        run: echo '::set-output name=value::future'
      - run: make ${{ steps.hugo-build-mode.outputs.value }}
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_SECRET }}
          external_repository: note-sarisia-cc/note-sarisia-cc.github.io
          publish_branch: master
          publish_dir: ./public
          cname: note.sarisia.cc
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "update note.sarisia.cc"
          description: "https://note.sarisia.cc"
