name: deploy to github pages

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/note-sarisia-cc/note-sarisia-cc-devcontainer
          runCmd: |
            make

      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "build note.sarisia.cc"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    permissions:
      id-token: write
      pages: write
    steps:
      - uses: actions/deploy-pages@v1
        id: deploy

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "deploy note.sarisia.cc"
          description: "${{ steps.deploy.outputs.page_url }}"
